"""UI text for the engine side (the install guide page the app shows). Same contract as Loc.cs:
the English string is the key, so an untranslated line falls back to the original wording instead
of disappearing.

Selection follows A1401_LANG (set by the Windows app, so both sides agree), then the process
locale. Chinese is the only translated language so far.

    A1401_LANG=zh-CN python3 -m p1401.guide ...
"""
import os

_FORCED = os.environ.get("A1401_LANG", "")

ZH = {
    # --- page furniture ---
    "1401 Install Guide": "1401 安装指南",
    "Firmware Prerequisite Review": "固件前置条件检查",
    " for this PC": " - 本机专用",
    "FIRMWARE REVIEW *** SAVED REPORT *** NO SETTINGS CHANGED": "固件检查 *** 已保存的报告 *** 未改动任何设置",
    "*** WRITTEN FOR THIS PC *** NOTHING ON THIS PAGE WAS SENT ANYWHERE *** TAKE A PHOTO BEFORE YOU OPEN THE BIOS *** 1401 IS FREE FOREVER ***":
        "*** 为本机生成 *** 本页内容未被发送到任何地方 *** 打开 BIOS 前请先拍照 *** 1401 永久免费 ***",
    "Hi! The 1401 app wrote this page on this PC, just for this PC &mdash; the settings below follow your scan and EFI. Exact firmware menus and board revisions have not been verified. Go through the steps in order and take your time.":
        "你好！1401 应用在本机生成了这个页面，也只适用于本机 &mdash; 下面的设置来自你的扫描结果和 EFI。确切的固件菜单名称和主板版本尚未经过核实。请按顺序逐步操作，不必着急。",
    "This local page reviews the selected report before any EFI build. It does not establish current firmware settings or driver support.":
        "这个本地页面在任何 EFI 构建之前检查所选报告。它不能确认当前的固件设置或驱动支持情况。",
    " The ones with a red <span class=\"star\">*</span> come first, before you touch the BIOS.":
        " 带红色 <span class=\"star\">*</span> 标记的步骤需要先完成，然后才能动 BIOS。",
    "This guide is for:": "本指南适用于：",
    "Steps": "步骤",
    "Show all the steps on one page": "在一页中显示全部步骤",
    "&lt; Back": "&lt; 返回",
    "Next &gt;": "下一步 &gt;",
    " steps": " 个步骤",
    "Step {} of {}": "第 {} 步，共 {} 步",
    "Back to the top": "回到顶部",
    "Board": "主板",
    "Type": "类型",
    "CPU": "CPU",
    "Graphics": "显卡",
    "macOS": "macOS",
    "BIOS SETTINGS FOR THIS PC ... print it, or take a photo of it":
        "本机的 BIOS 设置 ... 可以打印，或拍照留存",
    "Your scan: ": "扫描结果：",
    "already done": "已完成",
    "MUST": "必须",
    "optional": "可选",
    "must": "必须",
    "recommended": "建议",
    "(do this before changing the BIOS)": "（在改 BIOS 之前先做这一步）",
    "STOP!": "注意！",
    " Do this one before you change anything in the BIOS.": " 在改动 BIOS 任何设置之前，先做这一步。",
    "VIEWABLE WITH": "可用任意浏览器查看",
    "ANY BROWSER": "任意浏览器",
    "NO COOKIES": "无 Cookie",
    "NO TRACKING": "无追踪",
    "FREE": "永久免费",
    "FOREVER": "永久",
    "You are visitor number ": "你的访问编号是 ",
    " (it's only ever you &mdash; this page never left this PC)":
        "（永远只有你自己 &mdash; 这个页面从未离开本机）",
    "© 2026 NullMoth Systems": "© 2026 NullMoth Systems",
    "NullMoth and the moth logo are trademarks of NullMoth Systems.":
        "NullMoth 与飞蛾标志是 NullMoth Systems 的商标。",
    "Present day. Present time.": "此时此刻。",

    # --- step titles ---
    "Firmware prerequisite review": "固件前置条件检查",
    "Review the reported storage controllers": "检查报告中的存储控制器",
    "Protect Windows before changing storage": "改动存储前先保护好 Windows",
    "Check the exact firmware documentation": "查阅确切的主板说明书",
    "Before you start": "开始之前",
    "BitLocker (Windows drive encryption)": "BitLocker（Windows 磁盘加密）",
    "Windows is installed in Legacy (BIOS) mode": "Windows 安装在 Legacy（BIOS）模式",
    "Your drive controller is in RAID mode": "你的磁盘控制器处于 RAID 模式",
    "Make the macOS stick": "制作 macOS 启动盘",
    "Change these BIOS settings, then Save & Exit": "按下列设置修改 BIOS，然后保存退出",
    "Start from the stick": "从 U 盘启动",
    "Install macOS": "安装 macOS",

    # --- prerequisite body ---
    "This report matches the completed Check this PC run selected in the app.":
        "这份报告与应用中选中的\"检测本机\"运行结果一致。",
    "This is an imported, changed, incomplete or unbound report. Its contents are not verified observations of this PC. Run Check this PC again before relying on them.":
        "这是一份导入的、被改动过的、不完整的或未绑定的报告。其内容并不是对本机的已验证观测结果。请重新运行\"检测本机\"后再依赖这些内容。",
    "No EFI has been generated by this review. It does not read startup configuration or change firmware, storage, Windows or security settings.":
        "本次检查没有生成任何 EFI。它不会读取启动配置，也不会改动固件、存储、Windows 或安全设置。",
    "This page covers prerequisites only. A completed EFI gets its separate Your BIOS steps guide after a successful build.":
        "本页仅涵盖前置条件。构建成功后会另外生成一份\"你的 BIOS 设置步骤\"指南。",
    "The report lists: {}. Controller names do not establish which drive uses them or the current firmware mode.":
        "报告中列出：{}。控制器名称无法确定哪些磁盘在使用它们，也无法确定当前的固件模式。",
    "Intel VMD is a storage prerequisite that this builder cannot handle. A firmware change or a supported alternate storage path may be needed; a software update does not establish support.":
        "Intel VMD 属于本构建器无法处理的存储前置条件。可能需要改动固件或采用受支持的替代存储方案；软件更新并不能解决支持问题。",
    "Confirm the controller and storage mode against a fresh scan and the exact system's documentation before proceeding.":
        "继续之前，请对照最新的扫描结果和该型号的确切说明书确认控制器与存储模式。",
    "Back up important files and prepare Windows recovery media. Save and verify the BitLocker or device-encryption recovery key before any firmware or storage change; if encryption status is unknown, treat the key as required.":
        "备份重要文件并准备好 Windows 恢复介质。在改动任何固件或存储设置之前，先保存并验证 BitLocker 或设备加密的恢复密钥；如果加密状态未知，就按需要该密钥处理。",
    "Do not simply switch storage mode. Windows may stop with INACCESSIBLE_BOOT_DEVICE, and RAID or Optane volumes can lose access to data.":
        "不要直接切换存储模式。Windows 可能会因 INACCESSIBLE_BOOT_DEVICE 而无法启动，RAID 或 Optane 卷也可能因此无法访问数据。",
    "Use the PC or motherboard vendor's documented migration procedure for the exact model, firmware revision and drive arrangement. It must address existing RAID/Optane volumes and Windows boot-driver preparation. A generic Safe Mode sequence is not a verified procedure for every system.":
        "使用 PC 或主板厂商针对确切型号、固件版本和磁盘排列提供的迁移流程。该流程必须涵盖现有的 RAID/Optane 卷以及 Windows 启动驱动的准备工作。通用的安全模式步骤并不是对每台机器都经过验证的流程。",
    "If the vendor does not document a safe migration or the required setting is unavailable, stop and ask its support team. This app does not run migration commands or change security settings.":
        "如果厂商没有提供安全的迁移方案，或所需设置不可用，请停止操作并咨询其支持团队。本应用不会执行迁移命令，也不会改动安全设置。",
    "Use the exact board or PC manual to identify its storage controls. Menu names, supported modes and affected ports have not been verified by this scan; this page does not guess them.":
        "查阅确切的主板或 PC 说明书以确定其存储控制项。菜单名称、支持的模式以及受影响的接口均未经本次扫描核实；本页不会对此进行猜测。",
    "After a documented migration, verify that Windows boots normally and storage remains accessible. Then return to Check this PC and run a fresh scan before attempting Build again.":
        "按说明书完成迁移后，确认 Windows 能正常启动且存储仍可访问。然后回到\"检测本机\"重新扫描，再尝试构建。",
    "This review does not authorize creating or erasing a macOS stick. Complete a successful EFI build first.":
        "本次检查并未授权创建或清空 macOS 启动盘。请先完成一次成功的 EFI 构建。",

    # --- build guide body ---
    "Back up anything you can't lose. Installing macOS erases the disk you choose for it.":
        "备份任何你无法承受丢失的内容。安装 macOS 会清空你为它选择的磁盘。",
    "Install macOS on its own disk if you can. The installer erases the whole disk you pick, and that is the one step you can't undo.":
        "如果可以，请把 macOS 装在独立的磁盘上。安装程序会清空你选择的整块磁盘，这是唯一无法撤销的步骤。",
    "Have Ethernet ready. Many PC Wi-Fi cards don't work inside the macOS installer.":
        "准备好有线网络。很多 PC 的 Wi-Fi 网卡在 macOS 安装程序中无法使用。",
    "save your recovery key first (Settings -> Privacy & security -> Device encryption, or aka.ms/myrecoverykey). ":
        "请先保存你的恢复密钥（设置 -> 隐私与安全性 -> 设备加密，或访问 aka.ms/myrecoverykey）。",
    "Then the app pauses BitLocker for your next restarts. Changing Secure Boot with BitLocker running makes Windows ":
        "随后本应用会在接下来的几次重启中暂停 BitLocker。在 BitLocker 处于运行状态时更改 Secure Boot，会让 Windows ",
    "ask for that key.": "要求输入该密钥。",
    "BitLocker is ON on this PC. ": "本机的 BitLocker 已开启。",
    "The app couldn't tell whether BitLocker is on. If it is: ": "本应用无法确定 BitLocker 是否开启。如果已开启：",
    "macOS needs CSM off, and a Legacy-mode Windows stops booting once CSM is off.":
        "macOS 需要关闭 CSM，而 Legacy 模式的 Windows 在关闭 CSM 后将无法启动。",
    "Convert Windows to UEFI first, using Microsoft's built-in MBR2GPT tool: in an administrator terminal, run ":
        "请先用微软自带的 MBR2GPT 工具把 Windows 转换为 UEFI：以管理员身份打开终端，运行 ",
    "Back up before converting.": "转换之前请先备份。",
    "The app does this part. Use a USB stick of 4 GB or larger; everything on it is erased.":
        "这一步由本应用完成。请使用 4 GB 或更大的 U 盘；盘上的所有内容都会被清空。",
    "It writes this PC's boot files and downloads {} straight from Apple, checking every piece against Apple's signature.":
        "它会写入本机的启动文件，并直接从 Apple 下载 {}，逐项校验每个文件的 Apple 签名。",
    "Before you restart, take a photo of this page with your phone. You can't see it while you're in the BIOS.":
        "重启前，用手机把这个页面拍下来。在 BIOS 里你是看不到它的。",
    "Click **Restart into BIOS setup** in the app. Windows restarts straight into your BIOS setup.":
        "在应用中点击 **Restart into BIOS setup**。Windows 会直接重启进入 BIOS 设置。",
    "Restart and press the setup key as soon as the PC powers on.":
        "重启后，在电脑开机的瞬间按下设置键。",
    "If that doesn't work: restart and press [[{}]] repeatedly right after power-on.":
        "如果这样不行：重启后在开机的瞬间反复按 [[{}]]。",
    "These settings follow the scanned hardware and generated EFI. Menu names and vendor-family boot keys are suggestions; check the manual for the exact model and board revision. No firmware changes are automated.":
        "这些设置来自扫描到的硬件和生成的 EFI。菜单名称和厂商系列的启动按键仅供参考；请查阅说明书以确认确切的型号和主板版本。本应用不会自动改动任何固件设置。",
    "Change the settings below, then Save & Exit (on most boards [[F10]]). Let Windows start once to check it still boots.":
        "按下列设置修改后，选择保存退出（大多数主板是 [[F10]]）。让 Windows 启动一次，确认它仍能正常启动。",
    "Or restart and press your PC's boot-menu key (often F12, F11, F9 or Esc), then pick the USB stick marked UEFI.":
        "或者重启后按下你 PC 的启动菜单键（通常是 F12、F11、F9 或 Esc），然后选择标有 UEFI 的 U 盘。",
    "A boot menu appears. Pick the macOS installer (the entry ending in '(dmg)').":
        "会出现启动菜单。选择 macOS 安装程序（以 '(dmg)' 结尾的条目）。",
    "Quit Disk Utility, choose Reinstall macOS, and pick 'Macintosh HD'.":
        "退出磁盘工具，选择\"重新安装 macOS\"，然后选\"Macintosh HD\"。",
    "Keep the stick. For now it's how this PC starts macOS.":
        "保留这个 U 盘。目前本机就是靠它启动 macOS 的。",

    # --- RAID body ---
    "1. In an administrator terminal, run `bcdedit /set {current} safeboot minimal`, then restart into the BIOS.":
        "1. 以管理员身份打开终端，运行 `bcdedit /set {current} safeboot minimal`，然后重启进入 BIOS。",
    "2. Set SATA Mode to AHCI (or turn Intel VMD off), save, and let Windows start. It starts in Safe Mode.":
        "2. 把 SATA Mode 设为 AHCI（或关闭 Intel VMD），保存，然后让 Windows 启动。它会以安全模式启动。",
    "3. In Safe Mode, run `bcdedit /deletevalue {current} safeboot` and restart. Windows now boots normally on AHCI.":
        "3. 在安全模式中运行 `bcdedit /deletevalue {current} safeboot` 并重启。此后 Windows 在 AHCI 下可正常启动。",

    # --- merged forms of strings Python joins from adjacent literals ---
    "Above 4G Decoding": "Above 4G Decoding",
    " - turn it On": " - 请改为开启",
    "If that doesn't work: restart and press the setup key for your PC (usually Del, F2, F10 or F1; your manual names it).":
        "如果这样不行：重启后按下你这台 PC 的设置键（通常是 Del、F2、F10 或 F1；你的说明书上有说明）。",
    "Only after that, turn CSM off.": "完成之后才能关闭 CSM。",
    "Leave the stick plugged in. Click **Restart now and pick the USB stick (Use a device)** in the app. Windows restarts into its blue startup menu: choose Use a device, then your USB stick.":
        "保持 U 盘插着。在应用中点击 **Restart now and pick the USB stick (Use a device)**。Windows 会重启进入蓝色的启动菜单：选择\"使用设备\"，然后选择你的 U 盘。",
    "Or restart and press [[{}]] repeatedly as the PC starts, to open its boot menu, then pick the USB stick marked UEFI.":
        "或者重启后在电脑启动过程中反复按 [[{}]] 打开启动菜单，然后选择标有 UEFI 的 U 盘。",
    "Open Disk Utility -> View -> Show All Devices. Select the whole DISK you chose for macOS (not Windows' disk). Erase it as 'Macintosh HD', format APFS, scheme GUID Partition Map.":
        "打开\"磁盘工具\" -> \"显示\" -> \"显示所有设备\"。选择你为 macOS 准备的整块磁盘（不是 Windows 的磁盘）。将它抹掉为\"Macintosh HD\"，格式选 APFS，方案选 GUID 分区图。",
    "The PC restarts several times. Each time, start from the stick again and pick 'macOS Installer' until it becomes 'Macintosh HD'.":
        "电脑会重启数次。每次都从 U 盘启动并选择\"macOS 安装程序\"，直到它变成\"Macintosh HD\"。",
    "The scan found {}. macOS can't see drives in RAID/RST/VMD mode, so it has to change to AHCI, and Windows won't boot after that change unless you prepare it first:":
        "扫描发现 {}。macOS 无法看到处于 RAID/RST/VMD 模式的磁盘，因此需要改为 AHCI，否则改动之后 Windows 将无法启动，除非你事先做好准备：",

    # --- BIOS settings ---
    "Secure Boot": "Secure Boot",
    "Off": "关闭",
    "On": "开启",
    "On if you have it": "有此项则开启",
    "64M or more": "64M 或更大",
    "already off, nothing to change": "已关闭，无需改动",
    "the scan couldn't read it": "扫描未能读取该项",
    "It's usually on a Boot or Security tab.": "通常位于 Boot 或 Security 标签页。",
    " On ASUS boards, set Boot -> Secure Boot -> OS Type to 'Other OS'.":
        " 在 ASUS 主板上，把 Boot -> Secure Boot -> OS Type 设为\"其他操作系统\"。",
    "The macOS stick isn't signed by Microsoft, so a PC with Secure Boot on refuses to start it.":
        "macOS 启动盘没有微软签名，因此开启了 Secure Boot 的电脑会拒绝从它启动。",
    "CSM (Compatibility Support Module / Legacy boot)": "CSM（兼容性支持模块 / Legacy 启动）",
    "macOS starts only in pure UEFI mode. With CSM on, graphics often stall during boot.":
        "macOS 只能在纯 UEFI 模式下启动。开启 CSM 时，图形输出常在启动过程中卡住。",
    "Fast Boot (in the BIOS, not Windows)": "快速启动（BIOS 中的，不是 Windows 的）",
    "Fast Boot can skip USB setup, so the PC never sees the stick.":
        "快速启动可能跳过 USB 设备初始化，导致电脑根本看不到 U 盘。",
    "Required by the NVIDIA driver: it maps the card's full memory above 4 GB.":
        "NVIDIA 驱动需要此项：它会把显卡的全部内存映射到 4 GB 以上。",
    "currently {} - turn it On": "当前为 {} - 请改为开启",
    "currently {}": "当前为 {}",
    "Availability and menu names depend on the board and firmware. Check the exact board manual; if unavailable, stop and report it.":
        "该项是否提供以及菜单名称取决于主板和固件。请查阅确切的主板说明书；如果没有此项，请停止操作并反馈。",
    "Lets the GPU map its full memory. Your EFI already carries the workaround if it's missing.":
        "允许显卡映射全部内存。如果缺少该项，你的 EFI 已经内置了相应的规避方式。",
    "Lets the GPU map its full memory. Without it, macOS panics early on many graphics cards.":
        "允许显卡映射全部内存。没有它，许多显卡会让 macOS 在早期就内核崩溃。",
    "Most laptops don't show this setting. If yours doesn't, skip it.":
        "大多数笔记本不显示此项。如果你的机器也没有，跳过即可。",
    "If your BIOS doesn't have it, skip it.": "如果你的 BIOS 没有此项，跳过即可。",
    "Resizable BAR / Re-Size BAR": "Resizable BAR / Re-Size BAR",
    "Required by the NVIDIA driver: without it the screen stays on the startup text once the driver is in.":
        "NVIDIA 驱动需要此项：没有它，驱动加载后画面会一直停在启动文字上。",
    "On some boards it appears only after Above 4G Decoding is On, or after CSM is Off.":
        "有些主板只有在开启 Above 4G Decoding 或关闭 CSM 之后才会显示此项。",
    "Leave it {}": "保持为 {}",
    "Your EFI was built for this exact setting. If you change it, rebuild it in the app.":
        "你的 EFI 是针对这一确切设置构建的。如果改动它，需要在应用中重新构建。",
    "XHCI Hand-off (and EHCI Hand-off if listed)": "XHCI Hand-off（如果列出，也包括 EHCI Hand-off）",
    "Lets macOS take over the USB ports from the firmware.":
        "让 macOS 从固件手中接管 USB 端口。",
    "CFG Lock (MSR 0xE2 write protection)": "CFG Lock（MSR 0xE2 写保护）",
    "macOS writes a CPU power-management register that CFG Lock freezes.":
        "macOS 会写入一个 CPU 电源管理寄存器，而 CFG Lock 会将其冻结。",
    "Most BIOSes hide it. Skip it: your EFI already works around CFG Lock.":
        "大多数 BIOS 会隐藏此项。跳过即可：你的 EFI 已经规避了 CFG Lock。",
    "Your EFI does NOT work around this one, so it has to be off.":
        "你的 EFI 并未规避这一项，因此必须关闭。",
    "VT-d": "VT-d",
    "macOS's own VT-d handling conflicts with most PC firmware.":
        "macOS 自带的 VT-d 处理与大多数 PC 固件冲突。",
    "DVMT Pre-Allocated (iGPU memory)": "DVMT Pre-Allocated（核显内存）",
    "Gives Intel graphics enough memory for macOS's framebuffer.":
        "为 Intel 核显分配足够内存以支撑 macOS 的 framebuffer。",
    "Skip it if your BIOS doesn't show it; most laptops don't.":
        "如果你的 BIOS 没有此项就跳过；大多数笔记本都没有。",
    "IOMMU": "IOMMU",
    "The AMD IOMMU is a common cause of hangs early in the macOS boot.":
        "AMD IOMMU 是 macOS 启动早期卡死的常见原因。",
    "If your BIOS doesn't have this setting, skip it.": "如果你的 BIOS 没有此项，跳过即可。",

    # --- boot keys ---
    "Del or F2": "Del 或 F2",
    "F2 or Del": "F2 或 Del",
    "F2": "F2",
    "F10": "F10",
    "F1 (ThinkPad/ThinkCentre) or F2 (other Lenovo)": "F1（ThinkPad/ThinkCentre）或 F2（其他 Lenovo）",
    "Del": "Del",
    "F8": "F8",
    "F9 (or Esc for the startup menu)": "F9（启动菜单也可用 Esc）",
    "Esc": "Esc",
    "F11": "F11",
    "F12": "F12",
    "F12 (turn on 'F12 Boot Menu' in the BIOS first)": "F12（需先在 BIOS 中开启 'F12 Boot Menu'）",
}


def language():
    """'zh' when Chinese is selected, otherwise 'en'. Mirrors Loc.cs."""
    probe = _FORCED or os.environ.get("LANG", "") or ""
    return "zh" if probe.lower().startswith("zh") else "en"


def t(text):
    """The English string, or its Chinese translation. An untranslated string returns itself."""
    if language() != "zh":
        return text
    return ZH.get(text, text)


def f(text, *args):
    """A translated string with {} holes filled by str.format."""
    return t(text).format(*args)


def boot_keys(pairs):
    """Translates the vendor key pairs in guide.KEYS without touching the key letters themselves:
    F11 stays F11, only the surrounding wording is localized."""
    return tuple(t(k) for k in pairs)